version: "3"

services:
    app:
        container_name: ebxstatic-web
        image: ebxstatic-web
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./files:/static:ro
        ports:
            - "8080:80"

